"""initial baseline

Revision ID: 8b95b2f1710b
Revises: 
Create Date: 2026-08-30 16:28:18.780613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '8b95b2f1710b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # --- 手工补充：扩展与业务 schema（autogenerate 不会生成） ---
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_search")
    for schema in (
        "tutorials",
        "community_settings",
        "community",
        "forum",
        "conversation",
        "bot",
        '"user"',
        "ai_config",
        "content_filter",
    ):
        op.execute(f"CREATE SCHEMA IF NOT EXISTS {schema}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_providers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Provider 唯一标识名称'),
    sa.Column('provider_type', sa.String(length=50), nullable=False, comment='Provider 类型: gemini / deepseek / openai_compatible'),
    sa.Column('display_name', sa.String(length=200), nullable=False, comment='显示名称'),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False, comment='加密后的 API Key'),
    sa.Column('base_url', sa.Text(), nullable=True, comment='API 基础 URL'),
    sa.Column('extra', sa.JSON(), nullable=True, comment='额外配置参数 (JSON)'),
    sa.Column('enabled', sa.Integer(), nullable=False, comment='是否启用 (1=启用, 0=禁用)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='ai_config'
    )
    op.create_index('ix_ai_provider_name', 'ai_providers', ['name'], unique=True, schema='ai_config')
    op.create_table('ai_model_usage',
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('model_name'),
    schema='bot'
    )
    op.create_table('ai_prompts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('prompt_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='bot'
    )
    op.create_index('uq_ai_prompts_guild_name', 'ai_prompts', ['guild_id', 'prompt_name'], unique=True, schema='bot')
    op.create_table('blacklisted_users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'guild_id'),
    schema='bot'
    )
    op.create_table('channel_chat_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False, comment='频道ID或分类ID'),
    sa.Column('entity_type', sa.String(length=20), nullable=False, comment="'channel' 或 'category'"),
    sa.Column('is_chat_enabled', sa.Integer(), nullable=True, comment='可空，为空则继承上级'),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=True),
    sa.Column('cooldown_duration', sa.Integer(), nullable=True),
    sa.Column('cooldown_limit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='bot'
    )
    op.create_index('uq_channel_config_entity', 'channel_chat_config', ['guild_id', 'entity_id'], unique=True, schema='bot')
    op.create_table('channel_memory_anchors',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('anchor_message_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'channel_id'),
    schema='bot'
    )
    op.create_table('daily_model_usage',
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('usage_date', sa.String(length=10), nullable=False, comment='北京时间日期 YYYY-MM-DD'),
    sa.Column('provider_name', sa.String(length=100), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('model_name', 'usage_date'),
    schema='bot'
    )
    op.create_table('daily_stats',
    sa.Column('stat_date', sa.String(length=10), nullable=False, comment='北京时间日期 YYYY-MM-DD'),
    sa.Column('issue_user_warning_count', sa.Integer(), nullable=False),
    sa.Column('tarot_reading_count', sa.Integer(), nullable=False),
    sa.Column('forum_search_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('stat_date'),
    schema='bot'
    )
    op.create_table('global_chat_config',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_enabled', sa.Integer(), nullable=False),
    sa.Column('api_fallback_enabled', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('guild_id'),
    schema='bot'
    )
    op.create_table('global_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('key'),
    schema='bot'
    )
    op.create_table('globally_blacklisted_users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    schema='bot'
    )
    op.create_table('muted_channels',
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('muted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('muted_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('channel_id'),
    schema='bot'
    )
    op.create_table('user_channel_cooldown',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('last_message_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'channel_id'),
    schema='bot'
    )
    op.create_table('user_channel_timestamps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='bot'
    )
    op.create_index('idx_user_channel_ts', 'user_channel_timestamps', ['user_id', 'channel_id', 'timestamp'], unique=False, schema='bot')
    op.create_table('member_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False, comment='来自旧系统的唯一ID, 例如 member_id'),
    sa.Column('discord_id', sa.String(), nullable=True, comment='成员的Discord数字ID'),
    sa.Column('title', sa.Text(), nullable=True, comment='成员标题/昵称'),
    sa.Column('full_text', sa.Text(), nullable=False, comment='完整的成员档案文本，用于重新分块和BM25搜索'),
    sa.Column('source_metadata', sa.JSON(), nullable=True, comment='存储原始的、完整的成员档案'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('personal_summary', sa.Text(), nullable=True, comment='个人记忆'),
    sa.Column('history', sa.JSON(), nullable=True, comment='用于生成最近一次个人记忆'),
    sa.Column('personal_message_count', sa.Integer(), server_default='0', nullable=False, comment='个人消息计数'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_id'),
    sa.UniqueConstraint('external_id'),
    schema='community'
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False, comment='来源系统的唯一ID'),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=False, comment='完整的文本内容，用于重新分块和BM25搜索'),
    sa.Column('source_metadata', sa.JSON(), nullable=True, comment='完整元数据备份'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id'),
    schema='community_settings'
    )
    op.create_table('pending_entries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entry_type', sa.String(length=50), nullable=False, comment='条目类型'),
    sa.Column('data_json', sa.JSON(), nullable=False, comment='提交的原始数据'),
    sa.Column('message_id', sa.BigInteger(), nullable=False, comment='审核投票消息的ID'),
    sa.Column('channel_id', sa.BigInteger(), nullable=False, comment='提交所在频道ID'),
    sa.Column('guild_id', sa.BigInteger(), nullable=False, comment='提交所在服务器ID'),
    sa.Column('proposer_id', sa.BigInteger(), nullable=False, comment='提交者Discord ID'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending/approved/rejected'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='审核过期时间'),
    sa.PrimaryKeyConstraint('id'),
    schema='community_settings'
    )
    op.create_index('ix_cs_pending_status_expires', 'pending_entries', ['status', 'expires_at'], unique=False, schema='community_settings')
    op.create_table('content_filter_keywords',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('is_ignored', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='content_filter'
    )
    op.create_index('ix_cf_keyword_ignored', 'content_filter_keywords', ['is_ignored'], unique=False, schema='content_filter')
    op.create_index('ix_cf_keyword_unique', 'content_filter_keywords', ['keyword'], unique=True, schema='content_filter')
    op.create_table('conversation_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.String(length=50), nullable=False, comment='用户的Discord ID'),
    sa.Column('conversation_text', sa.Text(), nullable=False, comment='对话块的原始文本内容'),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='对话块中第一条消息的时间'),
    sa.Column('end_time', sa.DateTime(), nullable=False, comment='对话块中最后一条消息的时间'),
    sa.Column('message_count', sa.Integer(), nullable=False, comment='对话块中的消息数量'),
    sa.Column('bge_embedding', pgvector.sqlalchemy.halfvec.HALFVEC(dim=1024), nullable=True, comment='BGE-M3 模型的对话内容向量嵌入（用于语义搜索）'),
    sa.Column('qwen_embedding', pgvector.sqlalchemy.halfvec.HALFVEC(dim=1024), nullable=True, comment='Qwen3-Embedding-0.6B 模型的对话内容向量嵌入（用于语义搜索）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='数据库记录创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='数据库记录更新时间'),
    sa.PrimaryKeyConstraint('id'),
    schema='conversation'
    )
    op.create_index('idx_conv_bge_embedding_hnsw', 'conversation_blocks', ['bge_embedding'], unique=False, schema='conversation', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'bge_embedding': 'halfvec_cosine_ops'})
    op.create_index('idx_conv_discord_id', 'conversation_blocks', ['discord_id'], unique=False, schema='conversation')
    op.create_index('idx_conv_qwen_embedding_hnsw', 'conversation_blocks', ['qwen_embedding'], unique=False, schema='conversation', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'qwen_embedding': 'halfvec_cosine_ops'})
    op.create_index('idx_conv_start_time', 'conversation_blocks', ['start_time'], unique=False, schema='conversation')
    op.create_index(op.f('ix_conversation_conversation_blocks_id'), 'conversation_blocks', ['id'], unique=False, schema='conversation')
    op.create_table('backfill_status',
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('oldest_known_timestamp', sa.String(length=50), nullable=True),
    sa.Column('is_complete', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('channel_id'),
    schema='forum'
    )
    op.create_table('forum_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.BigInteger(), nullable=False, comment='Discord帖子的唯一ID'),
    sa.Column('thread_name', sa.Text(), nullable=False, comment='帖子标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='帖子完整内容（首楼）'),
    sa.Column('author_id', sa.BigInteger(), nullable=False, comment='作者的Discord ID'),
    sa.Column('author_name', sa.Text(), nullable=False, comment='作者的显示名称'),
    sa.Column('category_name', sa.Text(), nullable=False, comment='论坛频道名称（分类）'),
    sa.Column('channel_id', sa.BigInteger(), nullable=False, comment='父频道的Discord ID'),
    sa.Column('guild_id', sa.BigInteger(), nullable=False, comment='服务器的Discord ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='帖子创建时间（Discord时间）'),
    sa.Column('source_metadata', sa.JSON(), nullable=True, comment='来自旧系统的完整元数据备份'),
    sa.Column('bge_embedding', pgvector.sqlalchemy.halfvec.HALFVEC(dim=1024), nullable=True, comment='BGE-M3 模型的整帖内容向量嵌入（用于语义搜索）'),
    sa.Column('qwen_embedding', pgvector.sqlalchemy.halfvec.HALFVEC(dim=1024), nullable=True, comment='Qwen3-Embedding-0.6B 模型的整帖内容向量嵌入（用于语义搜索）'),
    sa.Column('created_at_db', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='数据库记录创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='数据库记录更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id'),
    schema='forum'
    )
    op.create_index('idx_forum_author', 'forum_threads', ['author_id'], unique=False, schema='forum')
    op.create_index('idx_forum_bge_embedding_hnsw', 'forum_threads', ['bge_embedding'], unique=False, schema='forum', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'bge_embedding': 'halfvec_cosine_ops'})
    op.create_index('idx_forum_category', 'forum_threads', ['category_name'], unique=False, schema='forum')
    op.create_index('idx_forum_channel', 'forum_threads', ['channel_id'], unique=False, schema='forum')
    op.create_index('idx_forum_created_at', 'forum_threads', ['created_at'], unique=False, schema='forum')
    op.create_index('idx_forum_qwen_embedding_hnsw', 'forum_threads', ['qwen_embedding'], unique=False, schema='forum', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'qwen_embedding': 'halfvec_cosine_ops'})
    op.create_index(op.f('ix_forum_forum_threads_id'), 'forum_threads', ['id'], unique=False, schema='forum')
    op.create_table('processed_threads',
    sa.Column('thread_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('thread_id'),
    schema='forum'
    )
    op.create_table('token_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_index(op.f('ix_token_usage_id'), 'token_usage', ['id'], unique=False)
    op.create_table('thread_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False, comment='Discord帖子的ID'),
    sa.Column('search_mode', sa.String(), nullable=False, comment="教程搜索模式: 'ISOLATED' (隔离) 或 'PRIORITY' (优先)"),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id'),
    schema='tutorials'
    )
    op.create_index(op.f('ix_tutorials_thread_settings_id'), 'thread_settings', ['id'], unique=False, schema='tutorials')
    op.create_table('tutorial_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False, comment='教程的标题。'),
    sa.Column('category', sa.String(), nullable=True, comment='教程所属的高级类别。'),
    sa.Column('source_url', sa.String(), nullable=True, comment='文档的源URL。'),
    sa.Column('author', sa.String(), nullable=True, comment='文档的作者名。'),
    sa.Column('author_id', sa.String(), nullable=False, comment='作者的Discord用户ID。'),
    sa.Column('thread_id', sa.String(), nullable=True, comment='原始Discord帖子的ID。'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='用于存储标签的JSON字段。'),
    sa.Column('original_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tutorials'
    )
    op.create_index('ix_tutorial_documents_author_id', 'tutorial_documents', ['author_id'], unique=False, schema='tutorials')
    op.create_index(op.f('ix_tutorials_tutorial_documents_id'), 'tutorial_documents', ['id'], unique=False, schema='tutorials')
    op.create_table('user_command_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户的Discord ID'),
    sa.Column('enabled_commands', sa.JSON(), nullable=True, comment='用户启用的命令列表（JSON格式），为null表示启用所有命令'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='user'
    )
    op.create_index(op.f('ix_user_user_command_settings_id'), 'user_command_settings', ['id'], unique=False, schema='user')
    op.create_table('user_memory_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户的Discord ID'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='记忆类别: emotion(情感) / status(状态) / preference(偏好) / positive_event(正面事件)'),
    sa.Column('content', sa.Text(), nullable=False, comment='记忆内容（单条不超过150字）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='user'
    )
    op.create_index('ix_user_memory_notes_user_category', 'user_memory_notes', ['user_id', 'category'], unique=False, schema='user')
    op.create_index(op.f('ix_user_user_memory_notes_id'), 'user_memory_notes', ['id'], unique=False, schema='user')
    op.create_index(op.f('ix_user_user_memory_notes_user_id'), 'user_memory_notes', ['user_id'], unique=False, schema='user')
    op.create_table('user_persona_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户的Discord ID'),
    sa.Column('persona_style', sa.String(length=50), nullable=False, comment='人设风格: default(默认) | gentle(温柔)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='user'
    )
    op.create_index(op.f('ix_user_user_persona_preference_id'), 'user_persona_preference', ['id'], unique=False, schema='user')
    op.create_table('user_tool_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户的Discord ID'),
    sa.Column('enabled_tools', sa.JSON(), nullable=True, comment='用户启用的工具列表（JSON格式），为null表示启用所有工具'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='user'
    )
    op.create_index(op.f('ix_user_user_tool_settings_id'), 'user_tool_settings', ['id'], unique=False, schema='user')
    op.create_table('user_warnings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('guild_id', sa.String(length=50), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='user'
    )
    op.create_index('ix_warnings_user_guild', 'user_warnings', ['user_id', 'guild_id'], unique=True, schema='user')
    op.create_table('ai_models',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False, comment='模型唯一标识 (如 deepseek-chat)'),
    sa.Column('display_name', sa.String(length=200), nullable=False, comment='模型显示名称'),
    sa.Column('provider_id', sa.BigInteger(), nullable=False, comment='所属 Provider ID'),
    sa.Column('actual_model', sa.String(length=200), nullable=False, comment='实际调用的模型名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='模型描述'),
    sa.Column('supports_vision', sa.Integer(), nullable=False, comment='是否支持视觉'),
    sa.Column('supports_tools', sa.Integer(), nullable=False, comment='是否支持工具调用'),
    sa.Column('supports_thinking', sa.Integer(), nullable=False, comment='是否支持思考模式'),
    sa.Column('max_output_tokens', sa.Integer(), nullable=False, comment='最大输出 token 数'),
    sa.Column('generation_config', sa.JSON(), nullable=True, comment='生成参数配置 (temperature, top_p 等)'),
    sa.Column('prompt_config', sa.JSON(), nullable=True, comment='提示词配置'),
    sa.Column('enabled', sa.Integer(), nullable=False, comment='是否启用 (1=启用, 0=禁用)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_config.ai_providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name'),
    schema='ai_config'
    )
    op.create_index('ix_ai_model_name', 'ai_models', ['model_name'], unique=True, schema='ai_config')
    op.create_index('ix_ai_model_provider', 'ai_models', ['provider_id'], unique=False, schema='ai_config')
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='分块在文档中的序号'),
    sa.Column('chunk_text', sa.Text(), nullable=False, comment='这个特定文本块的内容'),
    sa.Column('bge_embedding', pgvector.sqlalchemy.halfvec.HALFVEC(dim=1024), nullable=True, comment='BGE-M3 模型的嵌入向量。'),
    sa.Column('qwen_embedding', pgvector.sqlalchemy.halfvec.HALFVEC(dim=1024), nullable=True, comment='Qwen3-Embedding-0.6B 模型的嵌入向量。'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['community_settings.documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='community_settings'
    )
    op.create_index('idx_cs_bge_embedding_hnsw', 'chunks', ['bge_embedding'], unique=False, schema='community_settings', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'bge_embedding': 'halfvec_cosine_ops'})
    op.create_index('idx_cs_qwen_embedding_hnsw', 'chunks', ['qwen_embedding'], unique=False, schema='community_settings', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'qwen_embedding': 'halfvec_cosine_ops'})
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False, comment='这个特定文本块的内容。'),
    sa.Column('chunk_order', sa.Integer(), nullable=False, comment='文本块在文档中的序列号。'),
    sa.Column('bge_embedding', pgvector.sqlalchemy.halfvec.HALFVEC(dim=1024), nullable=True, comment='BGE-M3 模型的嵌入向量。仅在使用 BGE 模型的向量模式下写入。'),
    sa.Column('qwen_embedding', pgvector.sqlalchemy.halfvec.HALFVEC(dim=1024), nullable=True, comment='Qwen3-Embedding-0.6B 模型的嵌入向量。'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['tutorials.tutorial_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tutorials'
    )
    op.create_index('idx_bge_embedding_hnsw', 'knowledge_chunks', ['bge_embedding'], unique=False, schema='tutorials', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'bge_embedding': 'halfvec_cosine_ops'})
    op.create_index('idx_qwen_embedding_hnsw', 'knowledge_chunks', ['qwen_embedding'], unique=False, schema='tutorials', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'qwen_embedding': 'halfvec_cosine_ops'})
    op.create_index(op.f('ix_tutorials_knowledge_chunks_id'), 'knowledge_chunks', ['id'], unique=False, schema='tutorials')
    # --- 手工补充：ParadeDB BM25 索引（中文兼容分词，供混合检索的关键词路） ---
    op.execute("""
        CREATE INDEX idx_chunk_text_bm25
        ON tutorials.knowledge_chunks
        USING bm25 (id, ((chunk_text)::pdb.chinese_compatible))
        WITH (key_field=id);
    """)
    op.execute("""
        CREATE INDEX idx_cs_chunks_bm25
        ON community_settings.chunks
        USING bm25 (id, ((chunk_text)::pdb.chinese_compatible))
        WITH (key_field=id);
    """)
    op.execute("""
        CREATE INDEX idx_forum_content_bm25
        ON forum.forum_threads
        USING bm25 (id, ((content)::pdb.chinese_compatible), ((thread_name)::pdb.chinese_compatible))
        WITH (key_field=id);
    """)
    op.execute("""
        CREATE INDEX idx_conv_text_bm25
        ON conversation.conversation_blocks
        USING bm25 (id, ((conversation_text)::pdb.chinese_compatible))
        WITH (key_field=id);
    """)
    # --- 手工补充：清理 BM25 索引与业务 schema ---
    op.execute("DROP INDEX IF EXISTS tutorials.idx_chunk_text_bm25;")
    op.execute("DROP INDEX IF EXISTS community_settings.idx_cs_chunks_bm25;")
    op.execute("DROP INDEX IF EXISTS forum.idx_forum_content_bm25;")
    op.execute("DROP INDEX IF EXISTS conversation.idx_conv_text_bm25;")
    for schema in (
        "tutorials",
        "community_settings",
        "community",
        "forum",
        "conversation",
        "bot",
        '"user"',
        "ai_config",
        "content_filter",
    ):
        op.execute(f"DROP SCHEMA IF EXISTS {schema} CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tutorials_knowledge_chunks_id'), table_name='knowledge_chunks', schema='tutorials')
    op.drop_index('idx_qwen_embedding_hnsw', table_name='knowledge_chunks', schema='tutorials', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'qwen_embedding': 'halfvec_cosine_ops'})
    op.drop_index('idx_bge_embedding_hnsw', table_name='knowledge_chunks', schema='tutorials', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'bge_embedding': 'halfvec_cosine_ops'})
    op.drop_table('knowledge_chunks', schema='tutorials')
    op.drop_index('idx_cs_qwen_embedding_hnsw', table_name='chunks', schema='community_settings', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'qwen_embedding': 'halfvec_cosine_ops'})
    op.drop_index('idx_cs_bge_embedding_hnsw', table_name='chunks', schema='community_settings', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'bge_embedding': 'halfvec_cosine_ops'})
    op.drop_table('chunks', schema='community_settings')
    op.drop_index('ix_ai_model_provider', table_name='ai_models', schema='ai_config')
    op.drop_index('ix_ai_model_name', table_name='ai_models', schema='ai_config')
    op.drop_table('ai_models', schema='ai_config')
    op.drop_index('ix_warnings_user_guild', table_name='user_warnings', schema='user')
    op.drop_table('user_warnings', schema='user')
    op.drop_index(op.f('ix_user_user_tool_settings_id'), table_name='user_tool_settings', schema='user')
    op.drop_table('user_tool_settings', schema='user')
    op.drop_index(op.f('ix_user_user_persona_preference_id'), table_name='user_persona_preference', schema='user')
    op.drop_table('user_persona_preference', schema='user')
    op.drop_index(op.f('ix_user_user_memory_notes_user_id'), table_name='user_memory_notes', schema='user')
    op.drop_index(op.f('ix_user_user_memory_notes_id'), table_name='user_memory_notes', schema='user')
    op.drop_index('ix_user_memory_notes_user_category', table_name='user_memory_notes', schema='user')
    op.drop_table('user_memory_notes', schema='user')
    op.drop_index(op.f('ix_user_user_command_settings_id'), table_name='user_command_settings', schema='user')
    op.drop_table('user_command_settings', schema='user')
    op.drop_index(op.f('ix_tutorials_tutorial_documents_id'), table_name='tutorial_documents', schema='tutorials')
    op.drop_index('ix_tutorial_documents_author_id', table_name='tutorial_documents', schema='tutorials')
    op.drop_table('tutorial_documents', schema='tutorials')
    op.drop_index(op.f('ix_tutorials_thread_settings_id'), table_name='thread_settings', schema='tutorials')
    op.drop_table('thread_settings', schema='tutorials')
    op.drop_index(op.f('ix_token_usage_id'), table_name='token_usage')
    op.drop_table('token_usage')
    op.drop_table('processed_threads', schema='forum')
    op.drop_index(op.f('ix_forum_forum_threads_id'), table_name='forum_threads', schema='forum')
    op.drop_index('idx_forum_qwen_embedding_hnsw', table_name='forum_threads', schema='forum', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'qwen_embedding': 'halfvec_cosine_ops'})
    op.drop_index('idx_forum_created_at', table_name='forum_threads', schema='forum')
    op.drop_index('idx_forum_channel', table_name='forum_threads', schema='forum')
    op.drop_index('idx_forum_category', table_name='forum_threads', schema='forum')
    op.drop_index('idx_forum_bge_embedding_hnsw', table_name='forum_threads', schema='forum', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'bge_embedding': 'halfvec_cosine_ops'})
    op.drop_index('idx_forum_author', table_name='forum_threads', schema='forum')
    op.drop_table('forum_threads', schema='forum')
    op.drop_table('backfill_status', schema='forum')
    op.drop_index(op.f('ix_conversation_conversation_blocks_id'), table_name='conversation_blocks', schema='conversation')
    op.drop_index('idx_conv_start_time', table_name='conversation_blocks', schema='conversation')
    op.drop_index('idx_conv_qwen_embedding_hnsw', table_name='conversation_blocks', schema='conversation', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'qwen_embedding': 'halfvec_cosine_ops'})
    op.drop_index('idx_conv_discord_id', table_name='conversation_blocks', schema='conversation')
    op.drop_index('idx_conv_bge_embedding_hnsw', table_name='conversation_blocks', schema='conversation', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'bge_embedding': 'halfvec_cosine_ops'})
    op.drop_table('conversation_blocks', schema='conversation')
    op.drop_index('ix_cf_keyword_unique', table_name='content_filter_keywords', schema='content_filter')
    op.drop_index('ix_cf_keyword_ignored', table_name='content_filter_keywords', schema='content_filter')
    op.drop_table('content_filter_keywords', schema='content_filter')
    op.drop_index('ix_cs_pending_status_expires', table_name='pending_entries', schema='community_settings')
    op.drop_table('pending_entries', schema='community_settings')
    op.drop_table('documents', schema='community_settings')
    op.drop_table('member_profiles', schema='community')
    op.drop_index('idx_user_channel_ts', table_name='user_channel_timestamps', schema='bot')
    op.drop_table('user_channel_timestamps', schema='bot')
    op.drop_table('user_channel_cooldown', schema='bot')
    op.drop_table('muted_channels', schema='bot')
    op.drop_table('globally_blacklisted_users', schema='bot')
    op.drop_table('global_settings', schema='bot')
    op.drop_table('global_chat_config', schema='bot')
    op.drop_table('daily_stats', schema='bot')
    op.drop_table('daily_model_usage', schema='bot')
    op.drop_table('channel_memory_anchors', schema='bot')
    op.drop_index('uq_channel_config_entity', table_name='channel_chat_config', schema='bot')
    op.drop_table('channel_chat_config', schema='bot')
    op.drop_table('blacklisted_users', schema='bot')
    op.drop_index('uq_ai_prompts_guild_name', table_name='ai_prompts', schema='bot')
    op.drop_table('ai_prompts', schema='bot')
    op.drop_table('ai_model_usage', schema='bot')
    op.drop_index('ix_ai_provider_name', table_name='ai_providers', schema='ai_config')
    op.drop_table('ai_providers', schema='ai_config')
    # ### end Alembic commands ###
