"""Add general knowledge and community member tables

Revision ID: 048223358105
Revises: ec507c9addb9
Create Date: 2025-12-31 10:19:22.644413

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import HALFVEC

# revision identifiers, used by Alembic.
revision: str = "048223358105"
down_revision: Union[str, Sequence[str], None] = "ec507c9addb9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS community")
    op.execute("CREATE SCHEMA IF NOT EXISTS general_knowledge")
    op.create_table(
        "knowledge_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "external_id", sa.String(), nullable=False, comment="来自旧系统的唯一ID"
        ),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column(
            "searchable_text",
            sa.Text(),
            nullable=False,
            comment="用于全文搜索和向量化的文本内容",
        ),
        sa.Column(
            "source_metadata",
            sa.JSON(),
            nullable=True,
            comment="来自旧系统的完整元数据备份",
        ),
        sa.Column(
            "embedding", HALFVEC(3072), nullable=False, comment="文本内容的半精度向量"
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
        schema="general_knowledge",
    )
    op.create_table(
        "member_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "external_id",
            sa.String(),
            nullable=False,
            comment="来自旧系统的唯一ID, 例如 member_id",
        ),
        sa.Column(
            "discord_id", sa.String(), nullable=True, comment="成员的Discord数字ID"
        ),
        sa.Column(
            "searchable_text",
            sa.Text(),
            nullable=False,
            comment="用于全文搜索和向量化的文本内容, 例如个人简介、对话摘要等",
        ),
        sa.Column(
            "source_metadata",
            sa.JSON(),
            nullable=True,
            comment="存储原始的、完整的成员档案",
        ),
        sa.Column(
            "embedding", HALFVEC(3072), nullable=False, comment="文本内容的半精度向量"
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
        sa.UniqueConstraint("discord_id"),
        schema="community",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chunks", schema="general_knowledge")
    op.drop_table("chunks", schema="community")
    op.drop_table("documents", schema="general_knowledge")
    op.drop_table("documents", schema="community")
    op.execute("DROP SCHEMA IF EXISTS community")
    op.execute("DROP SCHEMA IF EXISTS general_knowledge")
    # ### end Alembic commands ###
