"""add_history_to_community_member_profile

Revision ID: 30a5bc392c20
Revises: 0d3c2d406343
Create Date: 2026-01-18 11:09:18.063443

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "30a5bc392c20"
down_revision: Union[str, Sequence[str], None] = "0d3c2d406343"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "member_profiles",
        sa.Column(
            "history", sa.JSON(), nullable=True, comment="用于生成最近一次个人记忆"
        ),
        schema="community",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("member_profiles", "history", schema="community")
    # ### end Alembic commands ###
