"""add personal_message_count to community_member_profiles

Revision ID: 40a238a8bfb3
Revises: 30a5bc392c20
Create Date: 2026-01-18 11:48:48.697994

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "40a238a8bfb3"
down_revision: Union[str, Sequence[str], None] = "30a5bc392c20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "member_profiles",
        sa.Column(
            "personal_message_count",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="个人消息计数",
        ),
        schema="community",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("member_profiles", "personal_message_count", schema="community")
    # ### end Alembic commands ###
