"""Phase 2: Create tables and indexes

Revision ID: 43ecab4319d0
Revises: 578adbc7c4bd
Create Date: 2025-12-18 12:56:45.311547

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = "43ecab4319d0"
down_revision: Union[str, Sequence[str], None] = "578adbc7c4bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tutorial_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False, comment="教程的标题。"),
        sa.Column(
            "category", sa.String(), nullable=True, comment="教程所属的高级类别。"
        ),
        sa.Column("source_url", sa.String(), nullable=True, comment="文档的源URL。"),
        sa.Column("author", sa.String(), nullable=True, comment="文档的作者。"),
        sa.Column("tags", sa.JSON(), nullable=True, comment="用于存储标签的JSON字段。"),
        sa.Column("original_content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="tutorials",
    )
    op.create_index(
        op.f("ix_tutorials_tutorial_documents_id"),
        "tutorial_documents",
        ["id"],
        unique=False,
        schema="tutorials",
    )
    op.create_table(
        "knowledge_chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column(
            "chunk_text", sa.Text(), nullable=False, comment="这个特定文本块的内容。"
        ),
        sa.Column(
            "chunk_order",
            sa.Integer(),
            nullable=False,
            comment="文本块在文档中的序列号。",
        ),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.HALFVEC(3072),
            nullable=False,
            comment="此文本块的半精度嵌入向量。",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["tutorials.tutorial_documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="tutorials",
    )

    # Corrected BM25 index creation using native SQL
    op.execute("""
        CREATE INDEX idx_chunk_text_bm25 
        ON tutorials.knowledge_chunks 
        USING bm25 (id, (chunk_text::pdb.chinese_compatible)) 
        WITH (key_field='id');
    """)

    op.create_index(
        "idx_embedding_hnsw",
        "knowledge_chunks",
        ["embedding"],
        unique=False,
        schema="tutorials",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        # 这是关键修复：指定列名对应的操作符类
        postgresql_ops={"embedding": "halfvec_cosine_ops"},
    )
    op.create_index(
        op.f("ix_tutorials_knowledge_chunks_id"),
        "knowledge_chunks",
        ["id"],
        unique=False,
        schema="tutorials",
    )
    # op.drop_table("_typmod_cache") # Removed as it's a system table for pg_search
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed create_table for _typmod_cache as it's a system table
    op.drop_index(
        op.f("ix_tutorials_knowledge_chunks_id"),
        table_name="knowledge_chunks",
        schema="tutorials",
    )
    op.drop_index(
        "idx_embedding_hnsw", table_name="knowledge_chunks", schema="tutorials"
    )

    # Correctly drop the BM25 index
    op.drop_index(
        "idx_chunk_text_bm25", table_name="knowledge_chunks", schema="tutorials"
    )

    op.drop_table("knowledge_chunks", schema="tutorials")
    op.drop_index(
        op.f("ix_tutorials_tutorial_documents_id"),
        table_name="tutorial_documents",
        schema="tutorials",
    )
    op.drop_table("tutorial_documents", schema="tutorials")
    # ### end Alembic commands ###
