"""refactor_general_knowledge_and_community_to_relational_tables

Revision ID: 8aaf3d1582e2
Revises: 048223358105
Create Date: 2026-01-11 08:24:57.204466

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import HALFVEC

# revision identifiers, used by Alembic.
revision: str = "8aaf3d1582e2"
down_revision: Union[str, Sequence[str], None] = "048223358105"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("member_entries", schema="community")
    op.drop_table("knowledge_entries", schema="general_knowledge")
    op.create_table(
        "member_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "external_id",
            sa.String(),
            nullable=False,
            comment="来自旧系统的唯一ID, 例如 member_id",
        ),
        sa.Column(
            "discord_id", sa.String(), nullable=True, comment="成员的Discord数字ID"
        ),
        sa.Column("title", sa.Text(), nullable=True, comment="成员标题/昵称"),
        sa.Column(
            "full_text",
            sa.Text(),
            nullable=False,
            comment="完整的成员档案文本，用于重新分块和BM25搜索",
        ),
        sa.Column(
            "source_metadata",
            sa.JSON(),
            nullable=True,
            comment="存储原始的、完整的成员档案",
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("discord_id"),
        sa.UniqueConstraint("external_id"),
        schema="community",
    )
    op.create_table(
        "knowledge_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "external_id", sa.String(), nullable=False, comment="来自旧系统的唯一ID"
        ),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column(
            "full_text",
            sa.Text(),
            nullable=False,
            comment="完整的文本内容，用于重新分块和BM25搜索",
        ),
        sa.Column(
            "source_metadata",
            sa.JSON(),
            nullable=True,
            comment="来自旧系统的完整元数据备份",
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
        schema="general_knowledge",
    )
    op.create_table(
        "member_chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column(
            "chunk_index", sa.Integer(), nullable=False, comment="分块在档案中的序号"
        ),
        sa.Column(
            "chunk_text", sa.Text(), nullable=False, comment="这个特定文本块的内容"
        ),
        sa.Column(
            "embedding",
            HALFVEC(3072),
            nullable=False,
            comment="此文本块的半精度嵌入向量",
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["community.member_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="community",
    )
    op.create_index(
        "idx_cm_embedding_hnsw",
        "member_chunks",
        ["embedding"],
        unique=False,
        schema="community",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "halfvec_cosine_ops"},
    )
    op.create_table(
        "knowledge_chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column(
            "chunk_index", sa.Integer(), nullable=False, comment="分块在文档中的序号"
        ),
        sa.Column(
            "chunk_text", sa.Text(), nullable=False, comment="这个特定文本块的内容"
        ),
        sa.Column(
            "embedding",
            HALFVEC(3072),
            nullable=False,
            comment="此文本块的半精度嵌入向量",
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["general_knowledge.knowledge_documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="general_knowledge",
    )
    op.create_index(
        "idx_gk_embedding_hnsw",
        "knowledge_chunks",
        ["embedding"],
        unique=False,
        schema="general_knowledge",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "halfvec_cosine_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_gk_embedding_hnsw",
        table_name="knowledge_chunks",
        schema="general_knowledge",
    )
    op.drop_table("knowledge_chunks", schema="general_knowledge")
    op.drop_index(
        "idx_cm_embedding_hnsw", table_name="member_chunks", schema="community"
    )
    op.drop_table("member_chunks", schema="community")
    op.drop_table("knowledge_documents", schema="general_knowledge")
    op.drop_table("member_profiles", schema="community")

    op.create_table(
        "knowledge_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "external_id", sa.String(), nullable=False, comment="来自旧系统的唯一ID"
        ),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column(
            "searchable_text",
            sa.Text(),
            nullable=False,
            comment="用于全文搜索和向量化的文本内容",
        ),
        sa.Column(
            "source_metadata",
            sa.JSON(),
            nullable=True,
            comment="来自旧系统的完整元数据备份",
        ),
        sa.Column(
            "embedding", HALFVEC(3072), nullable=False, comment="文本内容的半精度向量"
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
        schema="general_knowledge",
    )
    op.create_table(
        "member_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "external_id",
            sa.String(),
            nullable=False,
            comment="来自旧系统的唯一ID, 例如 member_id",
        ),
        sa.Column(
            "discord_id", sa.String(), nullable=True, comment="成员的Discord数字ID"
        ),
        sa.Column(
            "searchable_text",
            sa.Text(),
            nullable=False,
            comment="用于全文搜索和向量化的文本内容, 例如个人简介、对话摘要等",
        ),
        sa.Column(
            "source_metadata",
            sa.JSON(),
            nullable=True,
            comment="存储原始的、完整的成员档案",
        ),
        sa.Column(
            "embedding", HALFVEC(3072), nullable=False, comment="文本内容的半精度向量"
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("discord_id"),
        sa.UniqueConstraint("external_id"),
        schema="community",
    )
    # ### end Alembic commands ###
